# Generated by Django 2.2.8 on 2021-07-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191015_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'Standard'), (1, 'WithoutComments')], default=0),
        ),
    ]
