# Generated by Django 2.2.8 on 2021-07-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'StandardPost'), (1, 'Page')], default=0),
        ),
    ]
